version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
